spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
           git:
             uri: "https://github.com/eazybytes/eazybytes-config.git"
             default-label: main
             timeout: 5
             clone-on-start: true
             force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071
encrypt:
  key: "uV5oD1WQ2FzSpRXzW35upSL5Yb6H8zrj0wQ/DeS7JFs="
