spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts related QA APIs "
  contactDetails:
    name: "Smitha Roy - QA Leas"
    email: "sroy@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345