spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "2.0"

loans:
  message: "Welcome to EazyBank LOANS related local PROD APIs "
  contactDetails:
    name: "John Doe - PROD Developer"
    email: "john.prod@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
  