spring:
  config:
    activate:
      on-profile: "qa"
build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank LOANS related local QA APIs "
  contactDetails:
    name: "John Doe - QA Developer"
    email: "john.qa@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
  